[project]
name = "botanalisefundamentalista"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fundamentus>=0.3.2",
    "lxml>=6.0.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "yfinance>=0.2.66",
]
